// <auto-generated />
using System;
using Data.Models;
using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190902134912_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Lift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Lifts");
                });

            modelBuilder.Entity("Entities.Models.MainLift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LiftId");

                    b.Property<float>("MaxLift");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("UserId");

                    b.ToTable("MainLifts");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Entities.Models.SecondaryLift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LiftId");

                    b.Property<float>("MaxLift");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("UserId");

                    b.ToTable("SecondaryLifts");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsPound");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Models.MainLift", b =>
                {
                    b.HasOne("Entities.Models.Lift", "Lift")
                        .WithMany()
                        .HasForeignKey("LiftId");

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("MainLifts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Entities.Models.SecondaryLift", b =>
                {
                    b.HasOne("Entities.Models.Lift", "Lift")
                        .WithMany()
                        .HasForeignKey("LiftId");

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("SecondaryLifts")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
